### PR TITLE
Updated to .net 4.7

### PR DESCRIPTION
**Pull request by niemyjski**
I didn't run the tests due to they are not discovered in vs2017. It would be good to pull nunit from nuget and redo the structure to match the official ms structure but it works for now :)

### CODE REVIEW

**Comment by einaregilsson** [comment]
@niemyjski Thanks. I'll try to look into this sometime in the next couple of weeks.

**Comment by niemyjski** [comment]
I just wanted to let you know that I've been using this every day and it's been working great. I haven't noticed any issues

**Comment by einaregilsson** [comment]
Great. I finally have a Windows PC again so I'll try to get this merged and released soon.

**Comment by niemyjski** [comment]
Any updates on this?

**Comment by einaregilsson** [comment]
No, sorry, nothing yet. Don't have a Windows PC again now, and just haven't had time to look into this. Would you like to take this project over?

**Comment by niemyjski** [comment]
Sure, I'll help where I can :)

**Comment by einaregilsson** [comment]
Well, I've made you a collaborator. So, if the pull request is ready, feel free to merge it in, and maybe create a release with the compiled exe on https://github.com/einaregilsson/InsertIcons/releases (I think you can if you're a collaborator)

**Comment by niemyjski** [comment]
Thanks!

**Pull request merged**
